"""empty message

Revision ID: 30558611a9fc
Revises: 98187ef1de74
Create Date: 2022-07-31 13:40:31.707446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30558611a9fc'
down_revision = '98187ef1de74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['poster_id'], ['id'])
    op.drop_column('posts', 'author')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('posts', sa.Column('author', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
